export const LMS_PALETTE = {
  primary: 'var(--primary)',
  primaryActive: 'var(--primary)',
  canvas: 'var(--background)',
  surfaceSoft: 'var(--secondary)',
  surfaceCard: 'var(--card)',
  surfaceCreamStrong: 'var(--muted)',
  border: 'var(--border)',
  ink: 'var(--foreground)',
  body: 'var(--foreground)',
  muted: 'var(--muted-foreground)',
  mutedSoft: 'var(--muted-foreground)',
  dark: 'var(--card)',
  onDark: 'var(--card-foreground)',
  onDarkSoft: 'var(--muted-foreground)',
  teal: '#5db8a6',
  amber: '#e8a55a',
  success: '#5db872',
  warning: '#d4a017',
  error: '#c64545',
} as const
